class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'th': {
      'settings': 'ตั้งค่า',
      'dark_mode': 'โหมดกลางคืน (Dark Mode)',
      'language': 'ภาษา',
      'thai': 'ไทย',
      'english': 'อังกฤษ',
      'about_app': 'เกี่ยวกับแอปพลิเคชัน',
      'drug_management_system': 'ระบบจัดการยา v1.0',
      'login': 'เข้าสู่ระบบ',
      'username': 'ชื่อผู้ใช้',
      'password': 'รหัสผ่าน',
      'home': 'หน้าหลัก',
      'add_drug': 'เพิ่มยา',
      'logout': 'ออกจากระบบ',
      'location': 'สถานที่',
      'lam_luk_ka': 'ลำลูกกา',
      'ban_bueng': 'บ้านบึง',
      'head_office': 'สำนักงานใหญ่',
      'please_select_location': 'กรุณาเลือกสถานที่',
      'please_enter': 'กรุณากรอก',
      'login_success': 'เข้าสู่ระบบสำเร็จ',
      'login_failed': 'เข้าสู่ระบบไม่สำเร็จ',
      'invalid_credentials': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
      'network_error': 'เชื่อมต่อเซิร์ฟเวอร์ไม่ได้',
      'error_occurred': 'เกิดข้อผิดพลาด',
      'menu': 'เมนู',
      'drawer_title': 'เมนู',
      'search': 'ค้นหา',
      'no_drugs_found': 'ไม่พบข้อมูลยา',
      'inventory': 'คลังยา',
      'reports': 'รายงาน',
      'help': 'ช่วยเหลือ',
      'welcome': 'สวัสดี! 👋',
      'welcome_message': 'ยินดีต้อนรับสู่ระบบจัดการคลังยา',
      'all_drugs': 'ยาทั้งหมด',
      'expiring_soon': 'ใกล้หมดอายุ',
      'drug_categories': 'หมวดหมู่ยา',
      'recent_drugs': 'ยาล่าสุด',
      'see_all': 'ดูทั้งหมด',
      'items': 'รายการ',
      'stock': 'คงเหลือ',
      'low_stock': 'สต็อกต่ำ',
      'expiry': 'หมดอายุ',
      'notifications': 'การแจ้งเตือน',
      'user_guide': 'คู่มือการใช้งาน',
      'faq': 'คำถามที่พบบ่อย',
      'contact_support': 'ติดต่อสนับสนุน',
      'app_version': 'เวอร์ชันแอป',
      'help_dialog_title': 'ช่วยเหลือ',
      'user_guide_content': 'วิธีการใช้งานระบบจัดการยา:\n\n1. เพิ่มยาใหม่ในระบบ\n2. ตรวจสอบสต็อกยา\n3. ดูรายงานยาใกล้หมดอายุ\n4. จัดการหมวดหมู่ยา',
      'faq_content': 'คำถามที่พบบ่อย:\n\nQ: จะเพิ่มยาใหม่ได้อย่างไร?\nA: กดปุ่ม + ที่หน้าหลัก\n\nQ: จะดูยาที่ใกล้หมดอายุได้อย่างไร?\nA: ดูที่การ์ด "ใกล้หมดอายุ" ในหน้าหลัก',
      'contact_info': 'ติดต่อทีมสนับสนุน:\n\nEmail: sittikorn.pr@live.ku.th\nEmail: kitchakan.s@live.ku.th',
    },
    'en': {
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'thai': 'Thai',
      'english': 'English',
      'about_app': 'About Application',
      'drug_management_system': 'Drug Management System v1.0',
      'login': 'Login',
      'username': 'Username',
      'password': 'Password',
      'home': 'Home',
      'add_drug': 'Add Drug',
      'logout': 'Logout',
      'location': 'Location',
      'lam_luk_ka': 'Lam Luk Ka',
      'ban_bueng': 'Ban Bueng',
      'head_office': 'Head Office',
      'please_select_location': 'Please select location',
      'please_enter': 'Please enter',
      'login_success': 'Login successful',
      'login_failed': 'Login failed',
      'invalid_credentials': 'Invalid username or password',
      'network_error': 'Unable to connect to server',
      'error_occurred': 'An error occurred',
      'menu': 'Menu',
      'drawer_title': 'Menu',
      'search': 'Search',
      'no_drugs_found': 'No drugs found',
      'inventory': 'Inventory',
      'reports': 'Reports',
      'help': 'Help',
      'welcome': 'Hello! 👋',
      'welcome_message': 'Welcome to Drug Management System',
      'all_drugs': 'All Drugs',
      'expiring_soon': 'Expiring Soon',
      'drug_categories': 'Drug Categories',
      'recent_drugs': 'Recent Drugs',
      'see_all': 'See All',
      'items': 'items',
      'stock': 'Stock',
      'low_stock': 'Low Stock',
      'expiry': 'Expiry',
      'notifications': 'Notifications',
      'user_guide': 'User Guide',
      'faq': 'FAQ',
      'contact_support': 'Contact Support',
      'app_version': 'App Version',
      'help_dialog_title': 'Help',
      'user_guide_content': 'How to use Drug Management System:\n\n1. Add new drugs to the system\n2. Check drug inventory\n3. View expiring drugs report\n4. Manage drug categories',
      'faq_content': 'Frequently Asked Questions:\n\nQ: How to add new drugs?\nA: Press the + button on the home page\n\nQ: How to view expiring drugs?\nA: Check the "Expiring Soon" card on the home page',
      'contact_info': 'Contact Support Team:\n\nEmail: sittikorn.pr@live.ku.th\nEmail: kitchakan.s@live.ku.th',
    },
  };

  static String translate(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  static String get(String key, String languageCode) {
    return translate(key, languageCode);
  }
}
